# Generated by Django 3.1.2 on 2020-10-17 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chuanshanghui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFile',
            fields=[
                ('actfile_num', models.IntegerField(primary_key=True, serialize=False)),
                ('act_name', models.CharField(max_length=50)),
                ('actfile_name', models.CharField(max_length=50)),
                ('actfile_appendix', models.CharField(max_length=50)),
                ('check_if', models.IntegerField()),
                ('act_dp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chuanshanghui.department')),
            ],
        ),
        migrations.CreateModel(
            name='DpMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_post', models.CharField(max_length=6)),
                ('dp_num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chuanshanghui.department')),
                ('stu_num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chuanshanghui.people')),
            ],
        ),
        migrations.CreateModel(
            name='FundRecord',
            fields=[
                ('fund_num', models.AutoField(primary_key=True, serialize=False)),
                ('fund_for_matt', models.IntegerField()),
                ('fund_for_act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chuanshanghui.activityinfo')),
                ('fund_for_dp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chuanshanghui.department')),
            ],
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('reim_num', models.IntegerField(primary_key=True, serialize=False)),
                ('invo_appendix', models.CharField(max_length=50)),
                ('apply_time', models.DateTimeField(auto_now_add=True)),
                ('allow_time', models.DateTimeField(auto_now=True)),
                ('fund_pinchrage', models.BigIntegerField()),
                ('reim_state', models.CharField(max_length=6)),
                ('fund_num', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chuanshanghui.fundrecord')),
                ('reim_to', models.ForeignKey(max_length=2, on_delete=django.db.models.deletion.PROTECT, to='chuanshanghui.department')),
            ],
        ),
        migrations.CreateModel(
            name='MatterialRecord',
            fields=[
                ('m_num', models.IntegerField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=20)),
                ('m_stock', models.CharField(max_length=3)),
                ('m_borrow_sta', models.CharField(max_length=6)),
                ('m_pincharge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chuanshanghui.dpmembers', to_field='stu_num')),
            ],
        ),
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('coo_num', models.IntegerField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=20)),
                ('contact_if', models.IntegerField()),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('ddl', models.DateTimeField()),
                ('task_details', models.CharField(max_length=200)),
                ('task_note', models.CharField(max_length=200)),
                ('aappendix', models.CharField(max_length=50)),
                ('bappendix', models.CharField(max_length=50)),
                ('task_state', models.CharField(max_length=6)),
                ('adp_num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chuanshanghui.department', verbose_name='任务发布部门')),
                ('astu_num', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chuanshanghui.dpmembers', verbose_name='任务发布负责人')),
                ('bdp_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Department_bdp_num', to='chuanshanghui.department', verbose_name='任务接收部门')),
                ('bstu_num', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Department_bdp_num', to='chuanshanghui.dpmembers', verbose_name='任务接收负责人')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomRecord',
            fields=[
                ('classroom_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('classroom_cap', models.IntegerField()),
                ('classroom_borrowif', models.IntegerField()),
                ('classroom_pincharge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chuanshanghui.dpmembers', to_field='stu_num')),
            ],
        ),
        migrations.CreateModel(
            name='CheckYesActfile',
            fields=[
                ('check_num', models.IntegerField(primary_key=True, serialize=False)),
                ('check_dp', models.CharField(max_length=2)),
                ('check_state', models.CharField(max_length=6)),
                ('actfile_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chuanshanghui.activityfile')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('return_time', models.DateTimeField(auto_created=True)),
                ('borrow_num', models.IntegerField(primary_key=True, serialize=False)),
                ('borrow_type', models.CharField(choices=[('place', '场地'), ('matterial', '物资')], max_length=20)),
                ('borrow_name', models.CharField(max_length=20)),
                ('lent_for', models.CharField(max_length=200)),
                ('lent_time_range', models.DurationField()),
                ('lent_to_dp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chuanshanghui.department')),
                ('object_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chuanshanghui.matterialrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyFund',
            fields=[
                ('apply_num', models.IntegerField(primary_key=True, serialize=False)),
                ('apply_to', models.CharField(max_length=2)),
                ('apply_time', models.DateTimeField(auto_now_add=True)),
                ('allow_time', models.DateTimeField(auto_now_add=True)),
                ('apply_state', models.CharField(max_length=6)),
                ('fund_num', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chuanshanghui.fundrecord')),
                ('fund_pincharge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chuanshanghui.dpmembers', to_field='stu_num')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityFeedback',
            fields=[
                ('fb_num', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=300)),
                ('feedback_time', models.DateTimeField(auto_now_add=True)),
                ('act_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chuanshanghui.activityinfo')),
                ('stu_num', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chuanshanghui.dpmembers', to_field='stu_num')),
            ],
        ),
    ]
