# Generated by Django 3.1.1 on 2020-11-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chuanshanghui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityinfo',
            name='act_details',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='activityinfo',
            name='act_held_duration',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
