# Generated by Django 3.1.2 on 2020-10-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chuanshanghui', '0002_activityfeedback_activityfile_applyfund_borrowrecord_checkyesactfile_classroomrecord_cooperation_dpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityfile',
            name='actfile_appendix',
            field=models.FileField(upload_to='ActivityFile'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='aappendix',
            field=models.FileField(upload_to='Cooperation/a_Cooperation'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='bappendix',
            field=models.FileField(upload_to='Cooperation/b_Cooperation'),
        ),
    ]
