# Generated by Django 3.1.1 on 2020-11-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chuanshanghui', '0004_auto_20201123_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='bstu_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Department_bdp_num', to='chuanshanghui.dpmembers', verbose_name='任务接收负责人'),
        ),
    ]
