# Generated by Django 3.1.2 on 2020-11-12 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chuanshanghui', '0005_goodslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='astu_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chuanshanghui.dpmembers', to_field='stu_num', verbose_name='任务发布负责人'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='bstu_num',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Department_bdp_num', to='chuanshanghui.dpmembers', to_field='stu_num', verbose_name='任务接收负责人'),
        ),
    ]
