# Generated by Django 3.1.2 on 2020-11-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chuanshanghui', '0007_auto_20201113_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='adp_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chuanshanghui.department', verbose_name='任务发布部门'),
        ),
    ]
